name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    name: Builds and publishes package to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Pipenv
        run: make setup
      - name: Create test config
        run: |
          python -m notionsci config -f config.yml
          sed -i "s/<notion token>/${{ secrets.TEST_NOTION_TOKEN }}/g" config.yml
          sed -i "s/<notion unofficial token_v2>/${{ secrets.TEST_NOTION_TOKEN_V2 }}/g" config.yml
          sed -i "s/<zotero token>/${{ secrets.TEST_ZOTERO_TOKEN }}/g" config.yml
          sed -i "s/'123456'/${{ secrets.TEST_ZOTERO_LIB }}/g" config.yml
          sed -i "s/user/group/g" config.yml
      - name: Run Linter
        run: make lint-check
      - name: Run Tests
        run: make test
      - name: Package the project
        run: make package
      - name: Publish package to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish package to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}